Fix deadlock in Server Close()
holoplot/go-avahi pull request #1
Opened 2019-10-03 16:44 UTC by makon

Mainly this PR fixes the deadlock in Close().
I also has some minor fixes for the Readme and the unit tests.

I added a travis ci config file but unfortunatelly I can't configure it because I am not the owner of the repo. I would really appreciate it when you could set it up. It should be really easy. 
https://docs.travis-ci.com/user/tutorial/
https://docs.travis-ci.com/user/languages/go/

2020-02-28 15:17 UTC, zonque commented
Thanks for your contribution!

Unfortunately, this branch has outdated now, sorry for that. Could you rebase please?

2020-02-28 15:20 UTC, zonque requested changes
Please rebase and fix the style things, then we can quickly merge. Sorry for the delay on this, I was travelling for a longer while.

2020-02-28 15:20 UTC, zonque commented on server_test.go
> +
Stray newline?

2020-02-28 15:20 UTC, zonque commented on server.go
> +	c.quitChannel <- true
This could also become a `chan struct{}` I guess.

2020-02-28 15:20 UTC, zonque commented on server_test.go
> +
`go fmt` should also catch this :)

2020-03-27 12:16 UTC, zonque commented
Would you like to rebase this PR? I'd like like to merge this ...

2020-03-30 13:42 UTC, makon commented
Sorry for the late response, I will redo it on a new fork

2020-03-30 13:42 UTC, closed without merging